apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: podcast
  name: pvc-db-podcast
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 40Gi
