apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: podcast-backend
  name: podcast-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podcast-backend
  template:
    metadata:
      labels:
        app: podcast-backend
    spec:
      containers:
      - name: podcast-backend
        image: registry.tino.sh/podcast-app
        volumeMounts:
        - name: db-file
          mountPath: /opt
        env:
          - name: DBFILE
            valueFrom:
              configMapKeyRef:
                name: podcast-config
                key: DBFILE
          - name: FOLDER
            valueFrom:
              configMapKeyRef:
                name: podcast-config
                key: FOLDER
        resources:
          requests:
            memory: "120Mi"
            cpu: "300m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 30
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 20
          failureThreshold: 2
      volumes:
      - name: db-file
        persistentVolumeClaim:
          claimName: pvc-db-podcast
