apiVersion: v1
kind: Service
metadata:
  labels:
    app: podcast-app-service
  name: podcast-app-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: podcast-backend
